# Generated by Django 3.1.7 on 2021-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
    ]
