# Generated by Django 3.1.7 on 2021-03-31 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_isstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='isStudent',
        ),
    ]
