# Generated by Django 3.1.7 on 2021-03-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='company',
        ),
    ]
