# Generated by Django 3.1.7 on 2021-04-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210402_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github_link',
            new_name='linkedin_link',
        ),
    ]
