# Generated by Django 3.1.7 on 2021-04-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210402_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interns_hired',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='internship_post',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_of_employees',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
