# Generated by Django 3.1.7 on 2021-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210314_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isStudent',
            field=models.BooleanField(default=True),
        ),
    ]
