# Generated by Django 3.1.7 on 2021-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210331_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
